#!/bin/bash
## Functions
ServerConnect(){
  ~/.config/scs/bin/serverconnect
}

NewServer(){
  ~/.config/scs/bin/newserver
}

EditServer(){
  ~/.config/scs/bin/editserver
}

RemoveServer(){
  ~/.config/scs/bin/removeserver
}

## Defaults for all dialog boxes.
HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="Backtitle here"
TITLE="Title here"
MENU="Choose one of the following options:"

OPTIONS=(1 "Connect to server"
         2 "Add new server"
         3 "Edit server"
         4 "Remove Server"
         5 "Quit")

CHOICE=$(dialog --clear \
                  --backtitle "$BACKTITLE" \
                  --title "$TITLE" \
                  --menu "$MENU" \
                  $HEIGHT $WIDTH $CHOICE_HEIGHT \
                  "${OPTIONS[@]}" \
                  2>&1 >/dev/tty)






clear
case $CHOICE in
        1)
            ServerConnect
            ;;
        2)
            NewServer
            ;;
        3)
            EditServer
            ;;
        4)
            RemoveServer
            ;;
        5)
            break
            ;;
        *)
            echo "Incorrect input!"
            ;;
esac
